# https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_MAPPED_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      todos:
        aliases:
          - ${POSTGRES_DOCKER_HOSTNAME}

  db_init:
    image: ghcr.io/amacneil/dbmate
    restart: no
    depends_on:
      db:
        condition: service_healthy
    command: up
    volumes:
      - "./db:/db"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DOCKER_HOSTNAME}/${POSTGRES_DB}?sslmode=disable"
    networks:
      - todos
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - todos

volumes:
  pgdata:

networks:
  todos:

# docker run -it --rm --network db_default -e PGPASSWORD=hello postgres psql -h db -U hello 
# cat init.sql | docker run -i --rm --network db_default -e PGPASSWORD=hello postgres psql -h db -U hello 
