/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **todos**
   * - Table in database
   */
  export namespace todos {
    export type Table = 'todos';
    export interface Selectable {
      /**
      * **todos.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('todos_id_seq'::regclass)`
      */
      id: number;
      /**
      * **todos.description**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      description: string;
      /**
      * **todos.complete**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      complete: boolean;
    }
    export interface JSONSelectable {
      /**
      * **todos.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('todos_id_seq'::regclass)`
      */
      id: number;
      /**
      * **todos.description**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      description: string;
      /**
      * **todos.complete**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      complete: boolean;
    }
    export interface Whereable {
      /**
      * **todos.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('todos_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **todos.description**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      description?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **todos.complete**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      complete?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **todos.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('todos_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **todos.description**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      description: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **todos.complete**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      complete?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **todos.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('todos_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **todos.description**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      description?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **todos.complete**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      complete?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'todos_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = todos.Table;
    export type Selectable = todos.Selectable;
    export type JSONSelectable = todos.JSONSelectable;
    export type Whereable = todos.Whereable;
    export type Insertable = todos.Insertable;
    export type Updatable = todos.Updatable;
    export type UniqueIndex = todos.UniqueIndex;
    export type Column = todos.Column;
  
    export type AllBaseTables = [todos.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [todos.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "todos": todos.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "todos": todos.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "todos": todos.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "todos": todos.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "todos": todos.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "todos": todos.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "todos": todos.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "todos": todos.SQL;
  }[T];

}
